---
# Getting Values out of syncrou.manageiq-automate


- name: Get Package Info 
  hosts: localhost
  remote_user: "{{ my_local_user }}"
  connection: local
  gather_facts : no
  
  vars:
    - auto_commit: true
    - manageiq_validate_certs: false
      
  roles:
    - syncrou.manageiq-automate

  tasks:
    - name: "Set the job ID back into $evm.root"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attribute:
          object: "root"
          attribute: "tower_job_id"
          value:  "{{ tower_job_id }}"
          
    - name: "Get an attribute"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute: 
          object: "root"
          attribute: "::miq::parent"

    #- name: "Get a state_var"
    #  manageiq_automate:
    #    workspace: "{{ workspace }}"
    #    get_state_var:
    #      attribute: "task_id"
      
    - debug: 
        msg: "OUTPUT IIIIIII {{ tower_job_id }} IIIIIII OUTPUT"
