---
- name: Get Package Info 
  hosts: localhost
  remote_user: "{{ my_local_user }}"
  connection: local
  #become_method : sudo
  #become: yes
  gather_facts : no
  
  vars:
    - auto_commit: true
    - manageiq_validate_certs: false
      
  roles:
    - syncrou.manageiq-automate

  tasks:
  
    - name: "Set the job ID back into $evm.root"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attribute:
          object: "root"
          attribute: "tower_job_id"
          value:  "1158"
          
    - name: "Get an attribute"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute: "root"
          attribute: "ec2_ip"
      
    #- debug: msg="OUTPUT  OUTPUT OUTPUT  IIIIIII  {{ method_params }}   IIIIIII  OUTPUT  OUTPUT OUTPUT"
