---

# This install a ramdon website

- hosts: all
  connection: ssh
  remote_user: ec2-user
  become_method : sudo
  become: yes
  gather_facts : yes
  tasks:

  - name: Copy required application package
    copy:
      src: /root/
      dest: /root/
    with_items:
    - myAppCI.tar.gz
