---
# Make a call on REST API

- name: Make a call on REST API
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Make a call on REST API
    uri:
      url: "https://{{cfme_ip}}/api/automation_requests"
      method: POST
      validate_certs: false
      user: "{{ cfuser }}"
      password: "{{ cfpassword }}"
      body: '{ "version" : "1.1", "uri_parts" : { "namespace" : "mytest/General", "class" : "Methods", "instance" : "notifyEvent" }, "requester" : { "user_name" : "admin", "auto_approve" : true } }'
      body_format: json
      register: payloadop

  - name: Print command output
    action: command echo item
    with_items: payloadop.stdout
