---
# Make a call on REST API

- name: Make a call on REST API
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Make a call on REST API
    uri:
      url: "https://35.190.212.250/api"
      method: GET
      validate_certs: false
      user: "{{ cfuser }}"
      password: "{{ cfpassword }}"
      body: '{ "version" : "1.1", "uri_parts" : { "namespace" : "mytest/General", "class" : "Methods", "instance" : "notifyEvent" }, "requester" : { "user_name" : "admin", "auto_approve" : true } }'
      body_format: json
