---
- name: TEST TEST TEST TEST TEST PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts : no
  
  vars:
    - auto_commit: true
    - manageiq_validate_certs: false
      
  roles:
    - syncrou.manageiq-automate
  
  tasks:
         
    #- name: "Get an attribute"
    #  manageiq_automate:
    #    workspace: "{{ workspace }}"
    #    get_attribute:
    #      object: "/ManageIQ/System/Request/call_instance"
    #      attribute: "ec2_ip"
          
          
    - name: "Get the list of Method Parameters"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_method_parameters: yes
      register: method_params
