---
# Create a simple VM

- name: Create a simple VM instance
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    - auto_commit: true
    - manageiq_validate_certs: false
    
  roles:
    - syncrou.manageiq-automate
  
  tasks:
    - name: "Set the job ID back into $evm.root"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attribute:
          object: "root"
          attribute: "tower_job_id"
          value:  "{{ tower_job_id }}"

    - debug: msg=" WORKSPACE => {{ workspace }}  WWWWWWWW WORKSPACE ID => {{ workspace.id }}  WWWWWWWW TOWERJOBID => {{ tower_job_id }}"    

