---
- name: TEST TEST TEST TEST TEST PLAYBOOK
  hosts: localhost
  connection: local
  become_user: "{{ local_user }}"
  become_method : sudo
  become: yes
  gather_facts : no
  
  tasks:
  
    - name: "STARTING TEST PLAYBOOK"
      shell: yum info "{{ pkg }}"
      register: yum_output
      
    - debug: msg="OUTPUT TEST PLAYBOOK {{ yum_output }}"
