---
- name: TEST TEST TEST TEST TEST PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts : no
  
  tasks:
  
    - debug: 
        msg: "OUTPUT TOWERID {{ tower_job_id }} ===== OUTPUT WORKSPACE {{ workspace }}"
